services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: microhydros-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - microhydros-network
    restart: unless-stopped

  node-red:
    image: nodered/node-red:5.0.7
    container_name: microhydros-node-red
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    environment:
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
    networks:
      - microhydros-network
    depends_on:
      - mosquitto
    restart: unless-stopped

  influxdb:
    image: influxdb:2.9.1
    container_name: microhydros-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
    networks:
      - microhydros-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.2.1
    container_name: microhydros-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    networks:
      - microhydros-network
    depends_on:
      - influxdb
    restart: unless-stopped

networks:
  microhydros-network:
    driver: bridge

volumes:
  mosquitto_data:
  mosquitto_log:
  node_red_data:
  influxdb_data:
  influxdb_config:
  grafana_data:
